# Generated by Django 4.2.4 on 2023-08-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', '-start_date']},
        ),
    ]
